### ISSUE TITLE
tuning the model

### ISSUE THREAD

**Issue by eviling** [LukeAllen/optimeyes#7]
Hi Luke,

How can I tune the model? 
On the code you say something about tuning parameter lines which are:

`IRIS_RADIUS = gray.shape[0]*.75/2`
`magThreshold = magnitudeSquared.mean()*.6`
`isDark = gray< (gray.mean()*.8)`

What would it means if I increase or decrease the decimal numbers?

**Comment by LukeAllen** [comment]
Those are, respectively, the assumed size of the iris, the magnitude required before a gradient will be used to find the center of the iris, and the grayscale color of the iris. The PDF paper explains the basic operation of the algorithm. You'll need to read and understand the code if you want to tune it or make improvements though.
